version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: db

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

    volumes:
      - $(pwd)/docker/data:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=blueponny
      - MYSQL_DATABASE=myview
    
    ports:
      - 3306:3306

  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: myview

    command: >-
      gunicorn --bind 0:8000 myview.wsgi:application

    ports:
      - 8000:8000

    restart: always

    depends_on:
      - db